# Generated by Django 4.1.5 on 2023-01-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.URLField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menuitem'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
