# Generated by Django 4.1.5 on 2023-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_menuitem_level_remove_menuitem_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
